[tool.poetry]
name = "exploitutils"
version = "0.1.0"
description = ""
authors = ["Yanick Duchesne <yanickduchesne@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"


[tool.poetry.group.build.dependencies]
mypy = "^0.982"
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
